-- TRAINEES --

-- ALL FOLLOWING CALIBER_TRAINEE names were generated using https://name-generator.co.uk/quick
-- ANY LIKENESS IS CIRCUMSTANTIAL
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (1,'alex.smith@hotmail.com','Smith, Alex','TRAINING',2003,'123-867-5309',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5500,'alansmith@hotmail.com','Smith, Alan','DROPPED',2150,'123-867-5309',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5501,'csmith@hotmail.com','Smith, Charles','DROPPED',2150,'123-867-5309',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5502,'jsmith@gmail.com','Smith, John','DROPPED',2150,'123-867-5309',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5503,'cfranklin@test.com','Franklin, Ciaran','EMPLOYED',2200,'123-867-5309', null, null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5504,'ddeacon@test.com','Deacon, Dewey','EMPLOYED',2200,'123-867-5309', null, null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5505,'rwise@test.com','Wise, Rose','EMPLOYED',2200,'123-867-5309', null, null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5506,'sklein@test.com','Klein, Samantha','EMPLOYED',2200,'123-867-5309', null, null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5507,'hgranger@test.com','Granger, Heather','EMPLOYED',2200,'123-867-5309', null, null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5508,'nmine@test.com','Mine, Nathan','EMPLOYED',2200,'123-867-5309', null, null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5509,'abest@test.com','Best, Anthony','EMPLOYED',2200,'123-867-5309', null, null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5510,'tmiller@test.com','Miller, Tyler','EMPLOYED',2200,'123-867-5309', null, null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5511,'ahodgson@test.com','Hodgson, Aida','EMPLOYED',2200,'123-867-5309', null, null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5512,'mbrett@test.com','Brett, Mackenzie','EMPLOYED',2200,'123-867-5309', null, null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5513,'zbutler@test.com','Butler, Zidane','EMPLOYED',2200,'123-867-5309', null, null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5514,'rcalvert@test.com','Calvert, Richard','EMPLOYED',2200,'123-867-5309', null, null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5515,'vmedina@test.com','Medina, Victor','EMPLOYED',2200,'123-867-5309', null, null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5516,'dli@test.com','Li, Dante','EMPLOYED',2200,'123-867-5309', null, null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5517,'smartinez@test.com','Martinez, Scott','EMPLOYED',2200,'123-867-5309', null, null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5518,'ochase@test.com','Chase, Orion','DROPPED',2200,'123-867-5309',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5519,'sbenitez@test.com','Benitez, Sofia','DROPPED',2200,'123-867-5309',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5520,'emelendez@test.com','Melendez, Elsa','DROPPED',1,'123-867-5309',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5521,'criddle@test.com','Riddle, Clement','DROPPED',1,'123-867-5309',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5522,'rparry@test.com','Parry, Ruben','DROPPED',1,'123-867-5309',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5523,'hirvine@test.com.com','Irvine, Harry','DROPPED',1,'123-867-5309',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5524,'aphillip@test.com','Phillip, Alex','EMPLOYED',1,'123-867-5309', null, null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5525,'bbostock@test.com','Bostock, Bruce','EMPLOYED',1,'123-867-5309', null, null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5526,'bdraper@test.com','Draper, Bobby','EMPLOYED',1,'123-867-5309', null, null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5527,'adsmith@test.com.com','Smith, Adrian','EMPLOYED',1,'123-867-5309', null, null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5528,'fmarshall@test.com','Marshall, Fabian','EMPLOYED',1,'123-867-5309', null, null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5529,'lcardenas@test.com','Cardenas, Louis','EMPLOYED',1,'123-867-5309', null, null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5530,'syoung@test.com','Young, Shae','EMPLOYED',1,'123-867-5309', null, null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5531,'arusso@test.com','Russo, Atlas','TRAINING',1,'123-867-5309', null, null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5532,'jfrye@test.com','Frye, Jordan','EMPLOYED',1,'123-867-5309', null, null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5533,'lguerrero@test.com','Guerrero, Lacie','EMPLOYED',1,'123-867-5309', null, null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5534,'sbob@test.com','Bob, Sarah','EMPLOYED',1,'123-867-5309',null, null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5535,'strevino@test.com','Trevino, Sara','EMPLOYED',1,'123-867-5309', null, null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5536,'nzuniga@test.com','Zuniga, Nuala','EMPLOYED',1,'123-867-5309', null, null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5537,'tcote@test.com','Cote, Tyriq','EMPLOYED',1,'123-867-5309', null, null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5538,'awalls@test.com','Walls, Ava','EMPLOYED',1,'123-867-5309',null, null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5539,'afreeman@test.com','Freeman, Angela','EMPLOYED',1,'123-867-5309', null, null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5352,'ssweet@test.com','Sweet, Sannah','EMPLOYED',2050,'123-867-5309',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5350,'aparkes@test.com','Parkes, Anna','EMPLOYED',2050,'123-867-5309',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5351,'lholding@test.com','Holding, Lawrence','EMPLOYED',2050,'123-867-5309',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5353,'asargent@test.com','Sargent, Anna','EMPLOYED',2050,'123-867-5309',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5354,'kgross@test.com','Gross, Kevin','EMPLOYED',2050,'123-867-5309',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5355,'nodonnell@test.com','Odonnell, Natalie','EMPLOYED',2050,'123-867-5309',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5356,'rgomez@test.com','Gomez, Roxie','DROPPED',2050,'123-867-5309',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5357,'lbanks@test.com','Banks, Laura','DROPPED',2050,'123-867-5309',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5358,'mrudd@test.com.com','Rudd, Macauley','DROPPED',2050,'123-867-5309',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5359,'nhuff@test.com','Huff, Nia','DROPPED',2050,'123-867-5309',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5360,'mwainwright@test.com','Wainwright, Michael','EMPLOYED',2100,'123-867-5309',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5361,'bhogan@test.com','Hogan, Blake','EMPLOYED',2100,'123-867-5309',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5362,'lrocha@test.com','Rocha, Lukas','EMPLOYED',2100,'123-867-5309',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5363,'jking@test.com','King, Johan','EMPLOYED',2100,'123-867-5309',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5540,'kpratt@test.com','Pratt, Kaif','TRAINING',2150,null,null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5402,'smayer@test.com','Mayer, Sania','EMPLOYED',2100,'123-867-5309',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5400,'loctavia@test.com','Logan, Octavia','EMPLOYED',2100,'123-867-5309',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5401,'lalexander@test.com','Alexander, Lyne','EMPLOYED',2100,'123-867-5309',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5450,'hhensley@test.com','Hensley, Hughey','DROPPED',2100,'123-867-5309',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5451,'kfountain@test.com','Fountain, Kian','DROPPED',2100,'123-867-5309',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5452,'kcorey@test.com','Kenny, Corey','DROPPED',2100,'123-867-5309',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5453,'gwormald@test.com','Wormold, Giorgio','DROPPED',2100,'123-867-5309',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5454,'edaniels@test.com','Daniels, Esme','DROPPED',2100,'123-867-5309',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5455,'fmason@test.com','Mason, Fran','EMPLOYED',2100,'123-867-5309',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5456,'ssampson@test.com','Sampson, Sophie','EMPLOYED',2150,'123-867-5309',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5457,'wshelton@test.com','Shelton, Will','EMPLOYED',2150,'123-867-5309',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5458,'mmilano@test.com','Mayo, Milano','EMPLOYED',2150,'123-867-5309',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5459,'powen@test.com','Owen, Patrick','EMPLOYED',2150,'123-867-5309',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5460,'hwallace@test.com','Hayes, Wallace','EMPLOYED',2150,'123-867-5309',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5461,'mjackson@test.com','Jackson, Menna','EMPLOYED',2150,'123-867-5309',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5462,'bknights@test.com','Knights, Brendan','EMPLOYED',2150,'123-867-5309',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5463,'bholden@test.com','Holden, Bruno','EMPLOYED',2150,'123-867-5309',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5464,'mbright@test.com','Bright, Maariya','EMPLOYED',2150,'123-867-5309',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5465,'lbond@test.com','Bond, Leen','EMPLOYED',2150,'123-867-5309',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5466,'czahrah@test.com.com','Zahrah, Craig','EMPLOYED',2150,'123-867-5309',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5467,'asandoval@test.com','Sandoval, Asma','EMPLOYED',2150,'123-867-5309',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5468,'kkey@test.com.com','Key, Killian','DROPPED',2150,'123-867-5309',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5469,'lhinton@test.com','Hinton, Lorna','DROPPED',2150,'123-867-5309',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5470,'jtrujillo@test.com','Trujillo, Julian','DROPPED',2150,'123-867-5309',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5471,'epaterson@test.com','Paterson, Edwin','DROPPED',2150,'123-867-5309',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5472,'djarvis@test.com','Jarvis, Darci','DROPPED',2150,'123-867-5309',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5473,'wdean@test.com','Dean, Waseem','DROPPED',2150,'123-867-5309',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5474, 'dschrute@test.com','Schrute, Dwight','TRAINING',3000,'123-867-5309',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) values (5475, 'jhalpert@test.com','Halpert, Jim','TRAINING',3000,'123-867-5309',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) VALUES (5477, 'amartin@test.com','Martin, Andrew','TRAINING',2,'123-867-5309',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) VALUES (5478, 'kmalone@test.com','Malone, Kevin','TRAINING',2,'123-867-5309',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) VALUES (5479, 'abernard@test.com','Bernard, Andy','TRAINING',2,'123-867-5309',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) VALUES (5480, 'anorris@test.com','Norris, Annabella','TRAINING',3002,'123-867-5309',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) VALUES (5481, 'dhogg@test.com','Hogg, Daniella','TRAINING',3002,'123-867-5309',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) VALUES (5482, 'sford@test.com','Ford, Sapphire','TRAINING',3003,'123-867-5309',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) VALUES (5483, 'yrandolph@test.com','Randolph, Yusra','TRAINING',3003,'123-867-5309',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) VALUES (5484,'jcorssley@test.com','Crossley, Janet','TRAINING',3004,'123-867-5309',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) VALUES (5485,'latherton@test.com','Atherton, Lane','TRAINING',3004,'123-867-5309',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) VALUES (5486,'pwatson@test.com','Watson, Patrick','EMPLOYED',3005,'123-867-5309',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) VALUES (5487,'pwhitworth@test.com','Whitworth, Phill','EMPLOYED',3005,'123-867-5309',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) VALUES (5488,'lmarsh@test.com','Marsh, Lila','DROPPED',3006,'123-867-5309',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) VALUES (5489,'dhex@.com','Hex, Dewayne','TRAINING',3006,'123-867-5309',null,null);
INSERT INTO CALIBER_TRAINEE (TRAINEE_ID,TRAINEE_EMAIL,TRAINEE_NAME,TRAINING_STATUS,BATCH_ID,PHONE_NUMBER,PROFILE_URL,SKYPE_ID) VALUES (5490, 'dholcomb@test.com','Holcomb, Darryl','DROPPED',3003,'123-867-5309',null,null);

-- TRAINERS --
INSERT INTO CALIBER_TRAINER(TRAINER_ID, EMAIL, NAME, TITLE, TIER)
  VALUES( TRAINER_ID_SEQUENCE.NEXTVAL, 'patrick@test.com', 'Patrick Walsh', 'Lead Trainer', 'ROLE_VP');
INSERT INTO CALIBER_TRAINER(TRAINER_ID, EMAIL, NAME, TITLE, TIER)
  VALUES( TRAINER_ID_SEQUENCE.NEXTVAL, 'pjw6193@test.com', 'Dan Pickles', 'Lead Trainer', 'ROLE_VP');
INSERT INTO CALIBER_TRAINER(TRAINER_ID, EMAIL, NAME, TITLE, TIER)
  VALUES( TRAINER_ID_SEQUENCE.NEXTVAL, 'ravi.cto@test.com', 'Ravi Singh', 'Vice President of Technology', 'ROLE_VP');
INSERT INTO CALIBER_TRAINER(TRAINER_ID, EMAIL, NAME, TITLE, TIER)
  VALUES( TRAINER_ID_SEQUENCE.NEXTVAL, 'karan.svp@test.com', 'Karan Dhirar', 'Technology Manager', 'ROLE_VP');
INSERT INTO CALIBER_TRAINER(TRAINER_ID, EMAIL, NAME, TITLE, TIER)
  VALUES( TRAINER_ID_SEQUENCE.NEXTVAL, 'brian.retired@test.com', 'Brian Connolly', 'Senior Java Developer', 'ROLE_VP');
INSERT INTO CALIBER_TRAINER(TRAINER_ID, EMAIL, NAME, TITLE, TIER)
  VALUES( TRAINER_ID_SEQUENCE.NEXTVAL, 'genesis.bonds@test.com', 'Genesis Bonds', 'Trainer', 'ROLE_TRAINER');
INSERT INTO CALIBER_TRAINER(TRAINER_ID, EMAIL, NAME, TITLE, TIER)
  VALUES( TRAINER_ID_SEQUENCE.NEXTVAL, 'ankit.garg@test.com', 'Ankit Garg', 'Lead Trainer', 'ROLE_TRAINER');
INSERT INTO CALIBER_TRAINER(TRAINER_ID, EMAIL, NAME, TITLE, TIER)
  VALUES( TRAINER_ID_SEQUENCE.NEXTVAL, 'ryan.lessley@test.com', 'Ryan Lessley', 'Senior Trainer', 'ROLE_TRAINER');
INSERT INTO CALIBER_TRAINER(TRAINER_ID, EMAIL, NAME, TITLE, TIER)
  VALUES( TRAINER_ID_SEQUENCE.NEXTVAL, 'steven.kelsey@test.com', 'Steven Kelsey', 'Senior Trainer', 'ROLE_TRAINER');
INSERT INTO CALIBER_TRAINER(TRAINER_ID, EMAIL, NAME, TITLE, TIER)
  VALUES( TRAINER_ID_SEQUENCE.NEXTVAL, 'emily.higgins@test.com', 'Emily Higgins', 'Trainer', 'ROLE_TRAINER');
INSERT INTO CALIBER_TRAINER(TRAINER_ID, EMAIL, NAME, TITLE, TIER)
  VALUES( TRAINER_ID_SEQUENCE.NEXTVAL, 'taylor.kemper@test.com', 'Taylor Kemper', 'Senior Trainer', 'ROLE_TRAINER');
INSERT INTO CALIBER_TRAINER(TRAINER_ID, EMAIL, NAME, TITLE, TIER)
  VALUES( TRAINER_ID_SEQUENCE.NEXTVAL, 'richard.orr@test.com', 'Richard Orr', 'Trainer', 'ROLE_TRAINER');
INSERT INTO CALIBER_TRAINER(TRAINER_ID, EMAIL, NAME, TITLE, TIER)
  VALUES( TRAINER_ID_SEQUENCE.NEXTVAL, 'nickolas.jurczak@test.com', 'Nickolas Jurczak', 'Trainer', 'ROLE_TRAINER');
INSERT INTO CALIBER_TRAINER(TRAINER_ID, EMAIL, NAME, TITLE, TIER)
  VALUES( TRAINER_ID_SEQUENCE.NEXTVAL, 'august.duet@test.com', 'August Duet', 'Trainer', 'ROLE_TRAINER');
INSERT INTO CALIBER_TRAINER(TRAINER_ID, EMAIL, NAME, TITLE, TIER)
  VALUES( TRAINER_ID_SEQUENCE.NEXTVAL, 'yuvarajd@test.com', 'Yuvaraj Damodaran', 'Lead Trainer', 'ROLE_TRAINER');
INSERT INTO CALIBER_TRAINER(TRAINER_ID, EMAIL, NAME, TITLE, TIER)
  VALUES( TRAINER_ID_SEQUENCE.NEXTVAL, 'fred.belotte@test.com', 'Fred Belotte', 'Senior Trainer', 'ROLE_TRAINER');
INSERT INTO CALIBER_TRAINER(TRAINER_ID, EMAIL, NAME, TITLE, TIER)
  VALUES( TRAINER_ID_SEQUENCE.NEXTVAL, 'mehrab.rahman@test.com', 'Mehrab Rahman', 'Trainer', 'ROLE_TRAINER');
INSERT INTO CALIBER_TRAINER(TRAINER_ID, EMAIL, NAME, TITLE, TIER)
  VALUES( TRAINER_ID_SEQUENCE.NEXTVAL, 'peter.alagna@test.com', 'Peter Alagna', 'Trainer', 'ROLE_TRAINER');
INSERT INTO CALIBER_TRAINER(TRAINER_ID, EMAIL, NAME, TITLE, TIER)
  VALUES( TRAINER_ID_SEQUENCE.NEXTVAL, 'stanleym@test.com', 'Stanley Medikonda', 'Staging Manager', 'ROLE_STAGING');
INSERT INTO CALIBER_TRAINER(TRAINER_ID, EMAIL, NAME, TITLE, TIER)
  VALUES( TRAINER_ID_SEQUENCE.NEXTVAL, 'grawyne@gmail.com', 'Gray Wynne', 'Trainer', 'ROLE_TRAINER');
INSERT INTO CALIBER_TRAINER(TRAINER_ID, EMAIL, NAME, TITLE, TIER)
  VALUES(TRAINER_ID_SEQUENCE.NEXTVAL, 'owallace@test.com', 'Orson Wallace', 'Junior Trainer', 'ROLE_TRAINER');
INSERT INTO CALIBER_TRAINER(TRAINER_ID, EMAIL, NAME, TITLE, TIER)
  VALUES(TRAINER_ID_SEQUENCE.NEXTVAL, 'slevinson@test.com', 'Shelby Levinson', 'Junior Trainer', 'ROLE_TRAINER');
INSERT INTO CALIBER_TRAINER(TRAINER_ID, EMAIL, NAME, TITLE, TIER)
  VALUES(TRAINER_ID_SEQUENCE.NEXTVAL, 'wpayne@test.com', 'Walter Payne', 'Junior Trainer', 'ROLE_TRAINER');
INSERT INTO CALIBER_TRAINER(TRAINER_ID, EMAIL, NAME, TITLE, TIER)
  VALUES(TRAINER_ID_SEQUENCE.NEXTVAL, 'nchurch@test.com', 'Natalie Church', 'Junior Trainer', 'ROLE_TRAINER');
INSERT INTO CALIBER_TRAINER(TRAINER_ID, EMAIL, NAME, TITLE, TIER)
  VALUES(TRAINER_ID_SEQUENCE.NEXTVAL, 'aradcliff@test.com', 'Archer Radcliff', 'Junior Trainer', 'ROLE_TRAINER');
--------------------------------------------------------------------------------------------------------------------MAKE PANEL ROLE
INSERT INTO CALIBER_TRAINER(TRAINER_ID, EMAIL, NAME, TITLE, TIER)
  VALUES( TRAINER_ID_SEQUENCE.NEXTVAL, 'rajeshy@test.com', 'Rajesh Yamunachari', 'Senior Technical Manager', 'ROLE_PANEL');
INSERT INTO CALIBER_TRAINER(TRAINER_ID, EMAIL, NAME, TITLE, TIER)
  VALUES( TRAINER_ID_SEQUENCE.NEXTVAL, 'raghavan@test.com', 'Raghavan Swaminathan', 'Senior Technical Manager', 'ROLE_PANEL');
-------------TRAINER END-------------
INSERT INTO CALIBER_TRAINER(TRAINER_ID, EMAIL, NAME, TITLE, TIER)
  VALUES( TRAINER_ID_SEQUENCE.NEXTVAL, 'external@test.com', 'External Trainer', 'Trainer', 'ROLE_TRAINER');
INSERT INTO CALIBER_TRAINER(TRAINER_ID, EMAIL, NAME, TITLE, TIER)
  VALUES( TRAINER_ID_SEQUENCE.NEXTVAL, 'enrollmentadmin@test.com', 'Enrollment Admin', 'Bot User', 'ROLE_TRAINER');
INSERT INTO CALIBER_TRAINER(TRAINER_ID, EMAIL, NAME, TITLE, TIER)
  VALUES( TRAINER_ID_SEQUENCE.NEXTVAL, 'calibot@test.com', 'Caliber Bot', 'Bot User', 'ROLE_VP');
